config/routes.rb
Rails.application.routes.draw do

  resources :jobs

end

app/models/job.rb
class Job < ActiveRecord::Base

    validates_presence_of :title, :company, :min_salary, :location, :expire
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

    before_action :set_job, :only => [ :show, :edit, :update, :destroy]

    def index
        @jobs = Job.page(params[:page]).per(5)

        @job = Job.new
    end

    def new
        @job = Job.new
    end

    def create
        @job = Job.new(job_params)

        if @job.save
            flash[:notice] = "Job created successfully."

            redirect_to jobs_path
        else
            @jobs = Job.page(params[:page]).per(5)

            render :action => :new
        end
    end

    def show
    end

    def destroy
        @job.destroy

        flash[:alert] = "Job deleted successfully."
        redirect_to jobs_path
    end

    def edit
        @jobs = Job.page(params[:page]).per(5)
    end

    def update
        if @job.update(job_params)
            flash[:notice] = "Job updated successfully."

            redirect_to jobs_path
        else
            @jobs = Job.page(params[:page]).per(5)

            render :action => :edit
        end
    end

    def set_job
        @job = Job.find(params[:id])
    end

    def job_params
        params.require(:job).permit(:title,
            :company,
            :location,
            :min_salary,
            :url,
            :expire,
            :description)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<% if false %>
<% if j.errors.any? %>
      <ul>
      <% j.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
<% end %>
<% end %>

<div class="row form-inline">
    <div class="col-md-6">
        <div class="form-group">
            <%= f.label :title, "Job Title*" %>
            <%= f.text_field :title, :class => "form-control" %>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <%= f.label :company, "Company*" %>
            <%= f.text_field :company, :class => "form-control" %>
        </div>
    </div>

</div>

<div class="row form-inline">
    <div class="col-md-6">
        <div class="form-group">
            <%= f.label :location, "Location*" %>
            <%= f.text_field :location, :class => "form-control" %>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <%= f.label :min_salary, "Min. Salary*" %>
            <%= f.number_field :min_salary, :class => "form-control", :type => "number" %>
        </div>
    </div>
</div>

<div class="row form-inline">
    <div class="col-md-6">
        <div class="form-group">
            <%= f.label :expire, "Expire Date" %>
            <%= f.date_field :expire, :class => "form-control", :type => "date" %>
        </div>
    </div>
    <div class="col-md-6"></div>

</div>


<div class="form-group">
    <%= f.label :url, "Job URL" %>
    <%= f.text_field :url, :class => "form-control", :type => "url" %>
</div>

<div class="form-group">
    <%= f.label :description, "Description" %>
    <%= f.text_area :description, :class => "form-control", :rows => 3 %>
</div>

app/views/jobs/edit.html.erb
<h1>Outside Job Board</h1>

<%= debug(params) %>

<div id="edit_panel">
    <h3>Edit panel</h3>

    <% if @job %>
    <% if @job.errors.any? %>
        <div class="row">
            <div class="col">
                <ul>
                <% @job.errors.full_messages.each do |msg| %>
                <li class="bg-danger"><%= msg %></li>
                <% end %>
                </ul>
            </div>
        </div>
    <% end %>
    <% end %>

    <%= form_for @job, :url => job_path(@job, :page => params[:page]) do |f| %>
        <%= render :partial => 'form', :locals => { :f => f } %>
        <%= f.submit "Update", :class => "btn btn-primary" %>
    <% end %>

</div>

<% if false %>
<%= link_to new_job_path, :class => "btn btn-primary" do %>
    <span class="glyphicon glyphicon-plus"></span>張貼新的職缺
<% end %>
<% end %>

<table class="table table-striped table-hover">
        <tr>
            <td colspan="" rowspan="" headers="">職稱</td>
            <td>公司</td>
            <td>地點</td>
            <td>最低薪水</td>
            <td>網址</td>
            <td>到期日</td>
            <td></td>
        </tr>

    <% @jobs.each do |j| %>
        <tr>
            <td colspan="" rowspan="" headers=""><%= j.title %></td>
            <td><%= j.company %></td>
            <td><%= j.location %></td>
            <td><%= j.min_salary %></td>
            <td><%= j.url %></td>
            <td><%= j.expire %></td>
            <td>
                <%= link_to job_path(j), :class => "btn btn-primary" do %>
                    <span class="glyphicon glyphicon-info-sign"></span> 詳細資訊
                <% end %>

                <%= link_to edit_job_path(j, :page => params[:page]), :class => "btn btn-default" do %>
                    <span class="glyphicon glyphicon-pencil"></span> 編輯
                <% end %>

                <% if false %>
                <button class="btn btn-default" id="button_edit<%= j.id %>" onclick="toggle_edit_panel(<%= j.id %>);">
                    <span class="glyphicon glyphicon-pencil"></span> 編輯
                </button>
                <% end %>

                <%= link_to job_path(j), :method => :delete, :data => { :confirm => "Are you sure to delete?" }, :class => "btn btn-danger" do %>
                    <span class="glyphicon glyphicon-remove"></span> 刪除
                <% end %>
            </td>
        </tr>

    <% end %>

</table>
<%= will_paginate @jobs, renderer: BootstrapPagination::Rails, :params => { :controller => "jobs", :action => "index" } %>

app/views/jobs/index.html.erb
<h1>Outside Job Board</h1>

<% if false %>
<%= debug(params) %>
<% end %>

<button class="btn btn-primary" onclick="$('#new_panel').toggle();">
    <span class="glyphicon glyphicon-plus"></span>張貼新的職缺
</button>

<div id="new_panel" class="close_panel">
    <h3>張貼新的職缺</h3>

    <% if @job %>
    <% if @job.errors.any? %>
          <ul>
          <% @job.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
    <% end %>
    <% end %>

    <%= form_for @job, :url => jobs_path(:page => params[:page]) do |f| %>

        <%= render :partial => 'form', :locals => { :f => f } %>
        <%= f.submit "Post", :class => "btn btn-primary" %>

    <% end %>
</div>

<table class="table table-striped table-hover">
        <tr>
            <td colspan="" rowspan="" headers="">職稱</td>
            <td>公司</td>
            <td>地點</td>
            <td>最低薪水</td>
            <td>網址</td>
            <td>到期日</td>
            <td></td>
        </tr>

    <% @jobs.each do |j| %>
        <tr>
            <td colspan="" rowspan="" headers=""><%= j.title %></td>
            <td><%= j.company %></td>
            <td><%= j.location %></td>
            <td><%= j.min_salary %></td>
            <td><%= j.url %></td>
            <td><%= j.expire %></td>
            <td>
                <%= link_to job_path(j), :class => "btn btn-primary" do %>
                    <span class="glyphicon glyphicon-info-sign"></span> 詳細資訊
                <% end %>

                <%= link_to edit_job_path(j, :page => params[:page]), :class => "btn btn-default" do %>
                    <span class="glyphicon glyphicon-pencil"></span> 編輯
                <% end %>

                <% if false %>
                <button class="btn btn-default" id="button_edit<%= j.id %>" onclick="toggle_edit_panel(<%= j.id %>);">
                    <span class="glyphicon glyphicon-pencil"></span> 編輯
                </button>
                <% end %>

                <%= link_to job_path(j), :method => :delete, :data => { :confirm => "Are you sure to delete?" }, :class => "btn btn-danger" do %>
                    <span class="glyphicon glyphicon-remove"></span> 刪除
                <% end %>
            </td>
        </tr>

        <% if false %>
        <tr class="<% if @editing != j.id.to_s %>editarea<% end %> <% if @editing == j.id.to_s %>active<% end %>" id="edit<%= j.id %>">
            <td colspan="7">
                <h3>Edit panel</h3>

                <% if @job %>
                <% if @job.errors.any? %>
                      <ul>
                      <% @job.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                      <% end %>
                      </ul>
                <% end %>
                <% end %>

                <%= form_for j, :url => job_path(j) do |f| %>
                    <%= render :partial => 'form', :locals => { :f => f, :j => j } %>

                    <%= f.hidden_field :page, :value => params[:page] %>
                    <%= f.hidden_field :editing, :value => j.id %>

                    <%= f.submit "Update", :class => "btn btn-primary" %>

                <% end %>
            </td>
        </tr>
        <% end %>

    <% end %>

</table>
<%= will_paginate @jobs, renderer: BootstrapPagination::Rails %>

app/views/jobs/new.html.erb
<h1>Outside Job Board</h1>

<% if false %>
<%= debug(params) %>
<% end %>

<button class="btn btn-primary" onclick="$('#new_panel').toggle();">
    <span class="glyphicon glyphicon-plus"></span>張貼新的職缺
</button>

<div id="new_panel" class="">
    <h3>張貼新的職缺</h3>

    <% if @job %>
    <% if @job.errors.any? %>
          <ul>
          <% @job.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
    <% end %>
    <% end %>

    <%= form_for @job, :url => jobs_path(:page => params[:page]) do |f| %>

        <%= render :partial => 'form', :locals => { :f => f } %>
        <%= f.submit "Post", :class => "btn btn-primary" %>

    <% end %>
</div>

<table class="table table-striped table-hover">
        <tr>
            <td colspan="" rowspan="" headers="">職稱</td>
            <td>公司</td>
            <td>地點</td>
            <td>最低薪水</td>
            <td>網址</td>
            <td>到期日</td>
            <td></td>
        </tr>

    <% @jobs.each do |j| %>
        <tr>
            <td colspan="" rowspan="" headers=""><%= j.title %></td>
            <td><%= j.company %></td>
            <td><%= j.location %></td>
            <td><%= j.min_salary %></td>
            <td><%= j.url %></td>
            <td><%= j.expire %></td>
            <td>
                <%= link_to job_path(j), :class => "btn btn-primary" do %>
                    <span class="glyphicon glyphicon-info-sign"></span> 詳細資訊
                <% end %>

                <%= link_to edit_job_path(j, :page => params[:page]), :class => "btn btn-default" do %>
                    <span class="glyphicon glyphicon-pencil"></span> 編輯
                <% end %>

                <% if false %>
                <button class="btn btn-default" id="button_edit<%= j.id %>" onclick="toggle_edit_panel(<%= j.id %>);">
                    <span class="glyphicon glyphicon-pencil"></span> 編輯
                </button>
                <% end %>

                <%= link_to job_path(j), :method => :delete, :data => { :confirm => "Are you sure to delete?" }, :class => "btn btn-danger" do %>
                    <span class="glyphicon glyphicon-remove"></span> 刪除
                <% end %>
            </td>
        </tr>

        <% if false %>
        <tr class="<% if @editing != j.id.to_s %>editarea<% end %> <% if @editing == j.id.to_s %>active<% end %>" id="edit<%= j.id %>">
            <td colspan="7">
                <h3>Edit panel</h3>

                <% if @job %>
                <% if @job.errors.any? %>
                      <ul>
                      <% @job.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                      <% end %>
                      </ul>
                <% end %>
                <% end %>

                <%= form_for j, :url => job_path(j) do |f| %>
                    <%= render :partial => 'form', :locals => { :f => f, :j => j } %>

                    <%= f.hidden_field :page, :value => params[:page] %>
                    <%= f.hidden_field :editing, :value => j.id %>

                    <%= f.submit "Update", :class => "btn btn-primary" %>

                <% end %>
            </td>
        </tr>
        <% end %>

    <% end %>

</table>
<%= will_paginate @jobs, renderer: BootstrapPagination::Rails, :params => { :controller => "jobs", :action => "index" } %>

app/views/jobs/show.html.erb
<h1>Job Details</h1>

<ul>
    <li>Title: <%= @job.title %></li>
    <li>Company: <%= @job.company %></li>
    <li>Location: <%= @job.location %></li>
    <li>Min. Salary: <%= @job.min_salary %></li>
    <li>URL: <%= @job.url %></li>
    <li>Description: <%= @job.description %></li>
    <li>Expires: <%= @job.expire %></li>
</ul>

<%= link_to "Back to Index", jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
    <p class="bg-success"><%= flash[:notice] %></p>
    <p class="bg-danger"><%= flash[:alert] %></p>

    <%= yield %>
</div>


</body>
</html>